=== mloud1996/EnetComJavaProject/cvmodifier.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="cv">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Information_Personnel"/>
        <xs:element ref="Cursus_Universitaires"/>
        <xs:element ref="Competences"/>
        <xs:element ref="Projets"/>
        <xs:element ref="Langues"/>
        <xs:element ref="Stages"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Information_Personnel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nom" type="xs:string"/>
        <xs:element name="Prenom" type="xs:string"/>
        <xs:element name="Statut" type="xs:string"/>
        <xs:element name="Motivation" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cursus_Universitaires">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Diplome" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Diplome">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Etablissement" type="xs:string"/>
        <xs:element name="Série" type="xs:string" minOccurs="0"/>
        <xs:element name="Specialiter" type="xs:string" minOccurs="0"/>
        <xs:element ref="Année"/>
        <xs:element name="rang" type="xs:string" minOccurs="0"/>
        <xs:element name="Mention" type="xs:string" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="nom" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Année">
    <xs:complexType mixed="true">
      <xs:attribute name="DEBUT" type="xs:string"/>
      <xs:attribute name="FIN" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Competences">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Competence" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Competence">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="niveau" type="xs:string"/>
        <xs:element name="type" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="nom" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Projets">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Projet" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Projet">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="Sujet" type="xs:string"/>
        <xs:element name="Incubateur" type="xs:string"/>
        <xs:element name="Lieu" type="xs:string"/>
        <xs:element ref="Année"/>
        <xs:element name="Technologie" type="xs:string"/>
      </xs:choice>
      <xs:attribute name="nom" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Langues">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="langue" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="langue">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="niveau" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="nom" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Stages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Stage"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Stage">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Entreprise" type="xs:string"/>
        <xs:element name="Lieux" type="xs:string"/>
        <xs:element ref="Année"/>
        <xs:element name="Sujet" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="Intitule" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mloud1996/EnetComJavaProject/cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Maouloud%20breihile/Desktop/Video2brain%20Formation%20d%C3%A9couverte%20du%20langage%20XML/fichierXML/cvmodifier.xsd">
   <Information_Personnel>
             <Nom>MaouLoud</Nom>   
             <Prenom>Breihile</Prenom>
             <Statut>Eleve Ingenieur </Statut>
             <Motivation>Dynamique Motivé et Ambitieux</Motivation>
   </Information_Personnel>
   <Cursus_Universitaires>
             <Diplome   nom="Bac">
                       <Etablissement>Lyceé de Selibaby</Etablissement>
                       <Série>Mathématique</Série>
                       <Année>2016</Année>
                       <Mention>Assez Bien</Mention>
             </Diplome>
             <Diplome     nom="ConCour National Dingenieurie Mauritanien">
                       <Etablissement>Institut Preparatoire Au Grande Ecole Dingenieur </Etablissement>
                       <Specialiter>Math Physique Informatique</Specialiter>
                       <Année  DEBUT="08/09/2016"  FIN="08/07/2018"/>
                       <rang>73/120</rang>
             </Diplome>
             <Diplome     nom="Cycle Ingénieurs">
                       <Etablissement>Ecole Superieure Polytechnique </Etablissement>
                       <Specialiter>Informatique Réseaux et télécoms</Specialiter>
                       <Année  DEBUT="08/09/2018"  FIN="08/07/2020"/>
             </Diplome>
             <Diplome      nom="Double Diplomation">
                       <Etablissement>Ecole Nationale d'electronique et des télécommunications de Sfax</Etablissement>
                       <Specialiter>Genie des télécommunications</Specialiter>
                       <Année  DEBUT="2020"  FIN="2021"/>
             </Diplome>
   </Cursus_Universitaires>
   <Competences>
             <Competence       nom=" HTML/CSS/JAVASCRIPT " >
                       <niveau>Intermediaire</niveau>
                       <type>Language de programmation</type>
             </Competence>
             <Competence       nom=" JAVA/PYTHON/C " >
                       <niveau>Intermediaire</niveau>
                       <type>Language de programmation</type>
             </Competence>
             <Competence       nom=" Windows Server/Linux " >
                       <niveau>Intermediaire</niveau>
                       <type>System D'exploitation</type>
             </Competence>
             <Competence       nom=" Spring Boot /  Bootstrap /Strusts /Angular /Jquery " >
                      <niveau>Intermediaire</niveau>
                      <type>Framework</type>
             </Competence>
             <Competence       nom=" Mysql/Postgress " >
                       <niveau>Intermediaire</niveau>
                       <type>Base de donnée</type>
             </Competence>                      
             <Competence       nom=" JEE " >
                       <niveau>Intermediaire</niveau>
                       <type>Plateforme</type>
             </Competence>
             <Competence       nom=" Merise/UML " >
                       <niveau>Intermediaire</niveau>
                       <type>Methode de Conception de donneés</type>
             </Competence>
  </Competences>                    
   <Projets>
             <Projet   nom ="Projet de Creation innovation premier année ingénieur">
                     <Année>2018/2019</Année>
                     <Sujet>Conception et Creation d'un Drone pulverisateur</Sujet>
             </Projet>  
             <Projet   nom="Projet Industrielle deuxieme année ingénieur">
                   <Année>2019/2020</Année>
                   <Sujet>Recherche et Conception d'une Solution de transition de Ipv4 à Ipv6 au sein du reseaux Backbone de la societer Tunisienne des télécomunication Mattel</Sujet>
             </Projet>
             <Projet   nom="Projet de developpement informatique">
                   <Année>2019/2020</Année>
                   <Sujet>Developpement d'une application de Gestion d'emploi du temps en faveur de L'ESP</Sujet>
                   <Technologie>Spring Boot</Technologie>
             </Projet>
             <Projet   nom="Prix De Kosmos Entrepreneurship Competition">
                   <Sujet>Developpement d'une application de régularisation de l'irrigation</Sujet>
                   <Incubateur>Mauritanian Innovation Center</Incubateur>
                   <Lieu>Mauritanie/Nouakchott</Lieu>
                   <Année DEBUT="08/08/2019"   FIN="08/04/2020"/>
            </Projet>
   </Projets>
  <Langues>
            <langue   nom ="Français" >
               <niveau>Certificat  Dalf    C1 </niveau>  
            </langue>
            <langue   nom="Anglais" >
               <niveau>Intermediaire</niveau>
            </langue>
            <langue   nom="Arabe" >
               <niveau>Intermediaire</niveau>
            </langue>
  </Langues>   
  <Stages>
          <Stage    Intitule="Stage decouverte d'entreprise ">
               <Entreprise>Société Mauritanienne des Télécommunications Mauritel Mobile</Entreprise>
               <Lieux>Nouakchott</Lieux>
               <Année  DEBUT="08/08/2019"  FIN="08/09/2019"/>
               <Sujet>Decouverte du Réseaux GSM de Mauritel Mobile</Sujet>
          </Stage>
 </Stages>

</cv>
